#!/bin/sh
set -e

if [ -d /run/systemd/system ]; then
    case "$1" in
        remove|upgrade|deconfigure)
            systemctl stop shortp2p-messengerserver.service || true
            ;;
    esac
    if [ "$1" = remove ]; then
        systemctl disable shortp2p-messengerserver.service || true
    fi
fi

#DEBHELPER#

exit 0
