<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;$(NetCoreTargetFramework)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ShortP2P.MessengerServer.Domain</RootNamespace>
    <Description>Domain model for the ShortP2P messenger server.</Description>
  </PropertyGroup>

</Project>
