// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShortP2P.Discovery.RouteTables;

#nullable disable

namespace ShortP2P.Discovery.Migrations
{
    [DbContext(typeof(RouteDbContext))]
    [Migration("20260526112423_byte_12")]
    partial class byte_12
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ShortP2P.Discovery.RouteTables.PeerChain", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChainKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceRouteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("TargetNetworkId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChainKey")
                        .IsUnique();

                    b.HasIndex("TargetNetworkId");

                    b.ToTable("PeerChains");
                });

            modelBuilder.Entity("ShortP2P.Discovery.RouteTables.Route", b =>
                {
                    b.Property<string>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("RouteId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("ShortP2P.Discovery.RouteTables.PeerChain", b =>
                {
                    b.OwnsMany("ShortP2P.Discovery.RouteTables.PeerIdentityAddress", "PeerChainNodes", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("LastSeen")
                                .HasColumnType("TEXT");

                            b1.Property<int>("OrderIndex")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("PeerAddress")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<long>("PeerChainId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("RouteId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("PeerChainId", "OrderIndex");

                            b1.ToTable("PeerChainNodes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PeerChainId");

                            b1.OwnsOne("ShortP2P.Discovery.PeerIdentity", "PeerIdentity", b2 =>
                                {
                                    b2.Property<long>("PeerIdentityAddressId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("DataUdpPort")
                                        .HasColumnType("INTEGER");

                                    b2.Property<byte[]>("NetworkId")
                                        .IsRequired()
                                        .HasColumnType("BLOB");

                                    b2.Property<string>("Nickname")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("PeerIdentityAddressId");

                                    b2.ToTable("PeerChainNodes");

                                    b2.WithOwner()
                                        .HasForeignKey("PeerIdentityAddressId");
                                });

                            b1.Navigation("PeerIdentity")
                                .IsRequired();
                        });

                    b.Navigation("PeerChainNodes");
                });

            modelBuilder.Entity("ShortP2P.Discovery.RouteTables.Route", b =>
                {
                    b.OwnsMany("ShortP2P.Discovery.RouteTables.PeerIdentityAddress", "PeerRoutes", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("LastSeen")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PeerAddress")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("RouteId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("RouteId");

                            b1.ToTable("PeerIdentityAddress", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RouteId");

                            b1.OwnsOne("ShortP2P.Discovery.PeerIdentity", "PeerIdentity", b2 =>
                                {
                                    b2.Property<long>("PeerIdentityAddressId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("DataUdpPort")
                                        .HasColumnType("INTEGER");

                                    b2.Property<byte[]>("NetworkId")
                                        .IsRequired()
                                        .HasColumnType("BLOB");

                                    b2.Property<string>("Nickname")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("PeerIdentityAddressId");

                                    b2.ToTable("PeerIdentityAddress");

                                    b2.WithOwner()
                                        .HasForeignKey("PeerIdentityAddressId");
                                });

                            b1.Navigation("PeerIdentity")
                                .IsRequired();
                        });

                    b.Navigation("PeerRoutes");
                });
#pragma warning restore 612, 618
        }
    }
}
