// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShortP2P.Discovery.RouteTables;

#nullable disable

namespace ShortP2P.Discovery.Migrations
{
    [DbContext(typeof(RouteDbContext))]
    [Migration("20260424195505_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("ShortP2P.Discovery.RouteTables.Route", b =>
                {
                    b.Property<string>("RouteId")
                        .HasColumnType("TEXT");

                    b.HasKey("RouteId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("ShortP2P.Discovery.RouteTables.Route", b =>
                {
                    b.OwnsMany("ShortP2P.Discovery.RouteTables.PeerIdentityAddress", "PeerRoutes", b1 =>
                        {
                            b1.Property<string>("RouteId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("PeerAddress")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("RouteId", "Id");

                            b1.ToTable("PeerIdentityAddress");

                            b1.WithOwner()
                                .HasForeignKey("RouteId");

                            b1.OwnsOne("ShortP2P.Discovery.PeerIdentity", "PeerIdentity", b2 =>
                                {
                                    b2.Property<string>("PeerIdentityAddressRouteId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("PeerIdentityAddressId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("DataUdpPort")
                                        .HasColumnType("INTEGER");

                                    b2.Property<Guid>("NetworkId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Nickname")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("PeerIdentityAddressRouteId", "PeerIdentityAddressId");

                                    b2.ToTable("PeerIdentityAddress");

                                    b2.WithOwner()
                                        .HasForeignKey("PeerIdentityAddressRouteId", "PeerIdentityAddressId");
                                });

                            b1.Navigation("PeerIdentity")
                                .IsRequired();
                        });

                    b.Navigation("PeerRoutes");
                });
#pragma warning restore 612, 618
        }
    }
}
