<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(NetCoreTargetFramework)</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>ShortP2P.Auth</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="..\Shared\Require.cs" Link="Require.cs" />
        <Using Include="ShortP2P" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
        <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.13" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\ShortP2P.Crypto\ShortP2P.Crypto.csproj" />
    </ItemGroup>

</Project>
