<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- net8 for Server Auth; net10 for client apps -->
    <TargetFrameworks>net8.0;$(NetCoreTargetFramework)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' != 'net8.0'">
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="$(MicrosoftExtensionsVersion)" />
  </ItemGroup>

</Project>
