// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShortP2P.MessengerServer.Auth.EntityFramework;

#nullable disable

namespace ShortP2P.MessengerServer.Auth.EntityFramework.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260810090301_InitialAuthAccounts")]
    partial class InitialAuthAccounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("ShortP2P.MessengerServer.Auth.EntityFramework.Entities.AuthAccountEntity", b =>
                {
                    b.Property<string>("NetworkId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nick")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("NetworkId");

                    b.HasIndex("Nick")
                        .IsUnique();

                    b.ToTable("auth_accounts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
