// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShortP2P.MessengerServer.Persistence.Psql;

#nullable disable

namespace ShortP2P.MessengerServer.Persistence.Psql.Migrations
{
    [DbContext(typeof(MessengerDbContext))]
    [Migration("20260821180000_AddBlobs")]
    partial class AddBlobs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShortP2P.MessengerServer.Persistence.Psql.Entities.BlobRecord", b =>
                {
                    b.Property<string>("BlobId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("SrcNetworkId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TgtNetworkId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("BlobId");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("TgtNetworkId");

                    b.ToTable("blobs", (string)null);
                });

            modelBuilder.Entity("ShortP2P.MessengerServer.Persistence.Psql.Entities.ChatRecord", b =>
                {
                    b.Property<string>("ChatId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string>("NetworkIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("ChatId");

                    b.ToTable("chats", (string)null);
                });

            modelBuilder.Entity("ShortP2P.MessengerServer.Persistence.Psql.Entities.ChatRequestInboxRecord", b =>
                {
                    b.Property<string>("RequestId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TargetNetworkId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("RequestId", "DeviceId");

                    b.HasIndex("TargetNetworkId", "DeviceId");

                    b.ToTable("chat_request_inbox", (string)null);
                });

            modelBuilder.Entity("ShortP2P.MessengerServer.Persistence.Psql.Entities.ChatRequestRecord", b =>
                {
                    b.Property<string>("RequestId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequesterNetworkId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TargetNetworkId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("RequestId");

                    b.HasIndex("TargetNetworkId");

                    b.HasIndex("RequesterNetworkId", "TargetNetworkId");

                    b.ToTable("chat_requests", (string)null);
                });

            modelBuilder.Entity("ShortP2P.MessengerServer.Persistence.Psql.Entities.ClientStatusRecord", b =>
                {
                    b.Property<string>("NetworkId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("NetworkId", "DeviceId");

                    b.ToTable("client_statuses", (string)null);
                });

            modelBuilder.Entity("ShortP2P.MessengerServer.Persistence.Psql.Entities.CryptoKeysRecord", b =>
                {
                    b.Property<string>("SrcNetworkId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TgtNetworkId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SrcNetworkId", "TgtNetworkId");

                    b.ToTable("crypto_keys", (string)null);
                });

            modelBuilder.Entity("ShortP2P.MessengerServer.Persistence.Psql.Entities.DeliveryTicketRecord", b =>
                {
                    b.Property<string>("MessageId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MessageId");

                    b.ToTable("delivery_tickets", (string)null);
                });

            modelBuilder.Entity("ShortP2P.MessengerServer.Persistence.Psql.Entities.MessageInboxRecord", b =>
                {
                    b.Property<string>("MessageId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TgtNetworkId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("MessageId", "DeviceId");

                    b.HasIndex("TgtNetworkId", "DeviceId");

                    b.ToTable("message_inbox", (string)null);
                });

            modelBuilder.Entity("ShortP2P.MessengerServer.Persistence.Psql.Entities.MessageRecord", b =>
                {
                    b.Property<string>("MessageId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedDataBase64")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SrcNetworkId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TgtNetworkId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MessageId");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("SrcNetworkId");

                    b.HasIndex("TgtNetworkId");

                    b.ToTable("messages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
